### ISSUE TITLE
Agregar al proyecto un archivo con nombres de chocolates en varios idiomas

### ISSUE THREAD

**Issue by AliciaMstt** [AliciaMstt/Repo_chocolate#1]
Dar más detalles bla bla bla miau miau  guau guay priripripipi

**Comment by lmalpicas** [comment]
Tambien del pio pio y cuac cuac

**Comment by AliciaMstt** [comment]
Ok, entonces no es necesario poner los ejemplos mencionados. Este issue ya no es necesario.
